'use strict';

angular.module('propertySearchApp')
  .constant('paConfiguration', {
    clientAppName:"PropertySearch",
    clientAppNameGeo :"PropertySearch_Geo",
    initialExtentJson:{"xmin":807259.5478381776,"ymin":451155.83217993786,"xmax":965259.5478381779,"ymax":570822.4988466047,"spatialReference":{"wkid":2236}},
    wkidJson:{wkid:2236},
    urlPropertyAppraiser:"/PApublicServiceProxy/PaServicesProxy.ashx",
    urlAerialMap:"http://gisweb.miamidade.gov/ArcGIS/rest/services/MapCache/MDCImagery/MapServer",
    urlStreetMap:"http://gisweb.miamidade.gov/ArcGIS/rest/services/MapCache/BaseMap/MapServer",
    urlCoordFromFolio:"http://gisweb.miamidade.gov/ArcGIS/rest/services/MD_PA_PropertySearch/MapServer/19",
    urlParcelLayer:"http://gisweb.miamidade.gov/ArcGIS/rest/services/MD_PA_PropertySearch/MapServer/8",
    urlParcelBoundariesLayer:"http://gisweb.miamidade.gov/ArcGIS/rest/services/MD_PA_PropertySearch/MapServer/1",
    urlMunicipalityLayer:"http://gisweb.miamidade.gov/ArcGIS/rest/services/MD_PA_PropertySearch/MapServer/2",
    urlGeometryService:"http://gisweb.miamidade.gov/ArcGIS/rest/services/Geometry/GeometryServer/",
    urlLocatorService:"http://gisws.miamidade.gov/ArcGIS/rest/services/MDC_Locators/",
    aerials:{
             '2012':'http://imageserverintra.miamidade.gov/ArcGIS/rest/services/Orthos2012/ImageServer',
             '2010':'http://imageserverintra.miamidade.gov/ArcGIS/rest/services/Woolpert2010/ImageServer',
             '2009':'http://imageserverintra.miamidade.gov/ArcGIS/rest/services/PhotoScience2009/ImageServer',
             '2008':'http://imageserverintra.miamidade.gov/ArcGIS/rest/services/AerialsExpress2008/ImageServer',
            '2007':'http://imageserverintra.miamidade.gov/ArcGIS/rest/services/Woolpert2007/ImageServer',
             '2006':'http://imageserverintra.miamidade.gov/ArcGIS/rest/services/Woolpert2006/ImageServer',
             '2005':'http://imageserverintra.miamidade.gov/ArcGIS/rest/services/Woolpert2005/ImageServer',
             '2003':'http://imageserverintra.miamidade.gov/ArcGIS/rest/services/Woolpert2003/ImageServer',
             '2001':'http://imageserverintra.miamidade.gov/ArcGIS/rest/services/Woolpert2001/ImageServer',
             '1999':'http://imageserverintra.miamidade.gov/ArcGIS/rest/services/Woolpert1999/ImageServer'},
    additionalInfoUrls:{
      'Community Services Near Property':{label:'Community Services Near Property',
                                          url:'http://gisweb.miamidade.gov/communityservices/CommunityServicesAll.html',
                                          params:{x:null,y:null,bufferDistance:5,address:null}},
      'Community Services Application': {label:'Community Services Application',
                                         url:'http://gisweb.miamidade.gov/communityservices',
                                         params:{address:null}},
      'Business Incentives':{label:'Business Incentives',
                             url:'http://gisweb.miamidade.gov/businessincentive/default.aspx',
                             params:{searchType:'address', paramvalue:null}},
      'Environmental Considerations':{label:'Environmental Considerations',
                                      url:'http://gisweb.miamidade.gov/environmentalconsiderations/default.aspx',
                                      params:{searchtype:'address', paramvalue:null}}
    },
    additionalInfoLayers:{
      'Community Development District':{label:"Community Development District", 
                           url:"http://s0142357.miamidade.gov/ArcGIS/rest/services/MD_PropertySearchApp/MapServer/11",
                           attributes:["NAME"]},
      'Community Redevelopment Area':{label:"Community Redevelopment Area",
                           url:"http://s0142357.miamidade.gov/ArcGIS/rest/services/MD_PropertySearchApp/MapServer/12",
                           attributes:["LOCATION"]},
      'Empowerment Zone':{label:"Empowerment Zone",
                           url:"http://s0142357.miamidade.gov/ArcGIS/rest/services/MD_PropertySearchApp/MapServer/13",
                           attributes:["NAME"]},
      'Enterprise Zone':{label:"Enterprise Zone",
                           url:"http://s0142357.miamidade.gov/ArcGIS/rest/services/MD_PropertySearchApp/MapServer/14",
                           attributes:["NAME"]},
       'Zoning Land Use':{label:"Zoning Land Use",
                           url:"http://s0142357.miamidade.gov/ArcGIS/rest/services/MD_PropertySearchApp/MapServer/15",
                           attributes:["LU"]},
                          //'Zoning Land Use Description':{label:"Zoning Land Use Description",
                          //                          url:"http://s0142357.miamidade.gov/ArcGIS/rest/services/MD_PropertySearchApp/MapServer/5",
                          //                          attributes:["LUDESC"]},
       'Urban Development':{label:"Urban Development",
                           url:"http://s0142357.miamidade.gov/ArcGIS/rest/services/MD_PropertySearchApp/MapServer/16",
                           attributes:["UDB"]},
      'Zoning':{label:"Zoning",
                           url:"http://s0142357.miamidade.gov/ArcGIS/rest/services/MD_PropertySearchApp/MapServer/4",
                           attributes:["ZONE"]},
      'ZoningMunicipalities':{label:"ZoningMunicipalities",
                           url:"http://s0142357.miamidade.gov/ArcGIS/rest/services/MD_PropertySearchApp/MapServer/5",
                           attributes:["ZONE"]}},
    layers:[{label:"Municipality", value:false, url:"http://gisweb.miamidade.gov/ArcGIS/rest/services/MD_PA_PropertySearch/MapServer/2", layerSymbol:{"color":[0,34,102,100],
                                                                                                                                                      "outline":{"color":[0,34,102,255],
                                                                                                                                                                 "width":1,
                                                                                                                                                                 "type":"esriSLS",
                                                                                                                                                                 "style":"esriSLSSolid"},
                                                                                                                                                      "type":"esriSFS",
                                                                                                                                                      "style":"esriSFSSolid"},
             attributes:['NAME']},
            {label:"Zip Code", value:false, url:"http://gisweb.miamidade.gov/ArcGIS/rest/services/MD_PA_PropertySearch/MapServer/3", layerSymbol:{"color":[0,255,217,100],
                                                                                                                                                  "outline":{"color":[0,255,217,255],
                                                                                                                                                             "width":1,
                                                                                                                                                             "type":"esriSLS",
                                                                                                                                                             "style":"esriSLSSolid"},
                                                                                                                                                  "type":"esriSFS",
                                                                                                                                                  "style":"esriSFSSolid"},
             attributes:['ZIPCODE']},

            {label:"Commission District", value:false, url:"http://gisweb.miamidade.gov/ArcGIS/rest/services/MD_PA_PropertySearch/MapServer/9",layerSymbol:{"color":[166,42,42, 100],
                                                                                                                                                            "outline":{"color":[166,42,42,255],
                                                                                                                                                                       "width":1,
                                                                                                                                                                       "type":"esriSLS",
                                                                                                                                                                       "style":"esriSLSSolid"},
                                                                                                                                                            "type":"esriSFS",
                                                                                                                                                            "style":"esriSFSSolid"},
             attributes:['ID']}
            //            {label:"PA Zoning", value:false, url:"http://s0142357.miamidade.gov/ArcGIS/rest/services/MD_PropertySearchApp_test/MapServer/9", layerSymbol:{"color":[0,100,0,100],
            //                                      "outline":{"color":[0,100,0,255],
            //                                                 "width":1,
            //                                                 "type":"esriSLS",
            //                                                 "style":"esriSLSSolid"},
            //                                      "type":"esriSFS",
            //                                      "style":"esriSFSSolid"},
            //            attributes:['ZONEDESC']}
           ],


    propertyMarkerSymbol:{"color":[255,0,0,128],
			  "size":6,
                          "angle":0,
                          "xoffset":0,
                          "yoffset":0,
                          "type":"esriSMS",
			  "style":"esriSMSSquare",
			  "outline":{"color":[0,0,0,255],
                                     "width":1,
                                     "type":"esriSLS",
                                     "style":"esriSLSSolid"}
                         },
    propertyMarkerPictureSymbol:{
      "url":"images/map-pin-64.png", 
      "height":40,
      "width":40,
      "type":"esriPMS",
      "angle": 0
    },
    propertyBoundarySymbol:{"color":[0,0,0,0],
                            "outline":{"color":[255,0,0,255],
                                       "width":2,
                                       "type":"esriSLS",
                                       "style":"esriSLSSolid"},
                            "type":"esriSFS",
                            "style":"esriSFSSolid"}
  });
